apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: cityexplorer
    version: v1
  name: cityexplorer-v1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cityexplorer
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cityexplorer
        version: v1
    spec:
      containers:
      - image: eronbituchenik/cityexplorer:1.0.1-amd64
        imagePullPolicy: IfNotPresent
        name: cityexplorer
        ports:
        - containerPort: 8901
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp