apiVersion: v1
kind: Service
metadata:
  labels:
    app: restraunts
    service: restraunts
  name: restraunts
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8901
  selector:
    app: restraunts
  sessionAffinity: None
  type: ClusterIP

